# some stuff
document_title: Sliced Investing | Hedge Funds for everyone
main_image:

# css stuff
css:
  # Top header
  headerColor: '#ffffff'
  # Footer
  footerColor: '#333'
  # Main body image
  backgroundUrl: 'slicedinvesting-bg.png'
  # Sections
  sectionBackgroundColorOdd: '#fff'
  sectionBackgroundColorEven: '#f3f3f3'

# top-level stuff
product_name: Sliced Investing
main_tagline: Achieve premiere hedge fund returns today.
sub_tagline: Finally, a platform that allows you to find and invest in winning hedge funds.
button_text: Get exclusive access now

# footer stuff
footer_text: (c) Sliced Investing, All Rights Reserved.
twitter: slicedinvesting

sections:
  -
    n-columns: true
    title: How It Works
    nav_link: true
    nav_link_id: how-it-works

    columns:
      -
        image: how-it-works.png
        text: Investors can select and invest in hedge fund opportunities, while hedge funds can easily solicit investments.

  -
    n-columns: true
    title: 
    nav_link: true
    nav_link_id: team
    columns:
      -
        title: Investment Democracy
        image: investor.png
        resize: true
        rounded_corner: false
        text: Alongside other accredited investors, manage your own investments by choosing in which hedge funds to invest.

      -
        title: Full Transparency
        image: Transparency.png
        resize: true
        rounded_corner: false
        text: We are bringing hedge funds from opacity and privacy to their future in transparency and online presence.

      -
        title: Safe and Secure
        image: security.png
        resize: true
        rounded_corner: false
        text: A premiere world class platform requires the highest level of security measures. Your money is safe with us.

  -
    subscribe: true
    nav_link_id: signup
    nav_link: true
    title: Register to get access today!
