# some stuff
document_title: Sliced Investing | Hedge Funds for everyone
main_image:

# css stuff
css:
  # Top header
  headerColor: '#ffffff'
  # Footer
  footerColor: '#333'
  # Main body image
  backgroundUrl: 'hedgefund.png'
  # Sections
  sectionBackgroundColorOdd: '#fff'
  sectionBackgroundColorEven: '#f3f3f3'

# top-level stuff
product_name: Sliced Investing
main_tagline: Hedge Fund Crowdfunding
sub_tagline: Invest in Hedge Funds without the High Minimum.
button_text: Sign Up

subscribe-header: true
nav_link_id: false
nav_link: false
title: Sign Up


# footer stuff
footer_text: (c) Sliced Investing, All Rights Reserved.
twitter: slicedinvesting
facebook: slicedinvesting
linkedin: slicedinvesting

sections:
  -
    n-columns: true
    title: Grow with the pros
    nav_link: true
    nav_link_id: grow
    nav_link_title: About

    columns:
      -
        texts:
          -
            text: 1. Create an account and browse hedge fund(s) that match your risk and return profile.
            text_align: left
            margin: 2em
            font_size: 1em
          -
            text: 2. Invest alongside other investors so you don't need to meet minimum hedge fund requirements.
            text_align: left
            margin: 2em
            font_size: 1em
          -
            text: 3. Track your investments, conduct extensive analysis, and collaborate with other investors.
            text_align: left
            margin: 2em
            font_size: 1em

      -
        image: investor.png
        resize: false
        circle: true

  -
    n-columns: true
    title: 
    nav_link: false
    columns:
      -
        title: Investment Democratized
        image: democracy.png
        resize: true
        rounded_corner: false
        texts:
          -
            text: We make elite investment managers and their returns accessible to investors through crowdfunding the required minimum investments.
      -
        title: Full Transparency
        image: transparency-2.png
        resize: true
        rounded_corner: false
        texts:
          -
            text: We are bringing hedge funds from their roots in opacity and exclusivity to their future in transparency and online accessability.
      -
        title: Safe and Secure
        image: security.png
        resize: true
        rounded_corner: false
        texts:
          -
            text: We take the highest security measures to ensure your transactions are protected and proper due diligence occurs.
  -
    subscribe: true
    nav_link_id: signup
    nav_link: true
    title: Sign up to learn more!
    nav_link_title: Sign up
