# some stuff
document_title: Sliced Investing | Hedge Funds for everyone
main_image:

# css stuff
css:
  # Top header
  headerColor: '#ffffff'
  # Footer
  footerColor: '#333'
  # Main body image
  backgroundUrl: 'slicedinvesting-bg.png'
  # Sections
  sectionBackgroundColorOdd: '#fff'
  sectionBackgroundColorEven: '#f3f3f3'

# top-level stuff
product_name: Sliced Investing
main_tagline: Hedge fund crowdfunding.
sub_tagline: Finally, a platform that allows you to find and invest in winning hedge funds.
button_text: Get access

subscribe-header: true
nav_link_id: false
nav_link: false
title: Get access


# footer stuff
footer_text: (c) Sliced Investing, All Rights Reserved.
twitter: slicedinvesting

sections:
  -
    n-columns: true
    title: How It Works
    nav_link: true
    nav_link_id: how-it-works

    columns:
      -
        image: how-it-works.png
        text: Our platform allows accredited investors to select and invest in hedge fund opportunities, while also allowing hedge funds to solicit investments. Choose from several available syndicates based on your personal risk/return profile.
        text_align: center

  -
    n-columns: true
    title: 
    nav_link: true
    nav_link_id: team
    columns:
      -
        title: Democratized Investing
        image: investor.png
        resize: true
        rounded_corner: false
        text: Alongside other private investors, choose the right hedge fund investment for your portfolio.

      -
        title: Full Transparency
        image: transparency.png
        resize: true
        rounded_corner: false
        text: We are bringing hedge funds from their roots in opacity and privacy to their future in transparency and online presence.

      -
        title: Safe and Secure
        image: security.png
        resize: true
        rounded_corner: false
        text: We take the highest security measures to ensure your transactions are protected and proper due diligence occurs.

  -
    subscribe: true
    nav_link_id: signup
    nav_link: true
    title: Register to get access today!
